{% set name = "fusesoc" %}
{% set version = "1.11.0" %}

package:
  name : {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9256a1beb54d19a84471566ef972861f7101b4bd27d37e317f6fa5ed731d4a9e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm
  run:
    - python >=3
    - edalize >=0.2.2
    - ipyxact >=0.2.3
    - pyparsing
    - pyyaml
    - simplesat >=0.8.0

test:
  imports:
    - fusesoc

about:
  home: https://github.com/olofk/fusesoc/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: FuseSoC is a package manager and a set of build tools for FPGA/ASIC development

extra:
  recipe-maintainers:
    - hmaarrfk
